image:
  file: .gitpod/.gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: ddev
    init: |
      .gitpod/gitpod-setup-ddev.sh
      ./scripts/d7-data-setup.sh
      ./scripts/d9-empty-install.sh
      sudo ln -s $GITPOD_REPO_ROOT/.gitpod/preview-7.sh /usr/local/bin/preview7
      sudo ln -s $GITPOD_REPO_ROOT/.gitpod/preview.sh /usr/local/bin/preview
      sudo ln -s $GITPOD_REPO_ROOT/.gitpod/gitpod-setup-ddev.sh /usr/local/bin/gitpod-setup-ddev
    command: |
      .gitpod/gitpod-setup-ddev.sh
      echo "System is ready, clone a project, `ddev config` if needed, and `gitpod-setup-ddev` to run it"

# Set the following ports public
ports:
  - port: 6942
    onOpen: ignore
  - port: 8080
  - port: 8025
    onOpen: ignore
  - port: 8026
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8037
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 9999

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
