name = Citizen
description = Base 3 column layout with breakpoint and singularity.
preview = preview.png
template = citizen-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[hero]           = Hero

regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/citizen/citizen.layout.css
stylesheets[all][] = css/layouts/citizen/citizen.layout.no-query.css
stylesheets[all][] = css/layouts/citizen/citizen.styles.css

